const students =[{
    "id": 1,
    "first_name": "Deerdre",
    "last_name": "Garretson",
    "email": "dgarretson0@cargocollective.com",
    "gender": "Female",
    "ip_address": "149.164.121.19"
  }, {
    "id": 2,
    "first_name": "Cecil",
    "last_name": "Albinson",
    "email": "calbinson1@spiegel.de",
    "gender": "Non-binary",
    "ip_address": "101.141.141.32"
  }, {
    "id": 3,
    "first_name": "Rosalynd",
    "last_name": "Feldbrin",
    "email": "rfeldbrin2@cbslocal.com",
    "gender": "Genderqueer",
    "ip_address": "222.188.203.213"
  }, {
    "id": 4,
    "first_name": "Rebekah",
    "last_name": "Duggan",
    "email": "rduggan3@rediff.com",
    "gender": "Non-binary",
    "ip_address": "140.24.165.8"
  }, {
    "id": 5,
    "first_name": "Shandee",
    "last_name": "Caraher",
    "email": "scaraher4@weebly.com",
    "gender": "Male",
    "ip_address": "207.77.11.45"
  }, {
    "id": 6,
    "first_name": "Raffaello",
    "last_name": "Stanluck",
    "email": "rstanluck5@parallels.com",
    "gender": "Male",
    "ip_address": "236.150.175.239"
  }, {
    "id": 7,
    "first_name": "Luce",
    "last_name": "Schoular",
    "email": "lschoular6@dailymail.co.uk",
    "gender": "Non-binary",
    "ip_address": "147.46.131.239"
  }, {
    "id": 8,
    "first_name": "Mallory",
    "last_name": "Appleton",
    "email": "mappleton7@photobucket.com",
    "gender": "Female",
    "ip_address": "244.137.136.42"
  }, {
    "id": 9,
    "first_name": "Bendix",
    "last_name": "Maggi",
    "email": "bmaggi8@diigo.com",
    "gender": "Genderfluid",
    "ip_address": "157.173.175.195"
  }, {
    "id": 10,
    "first_name": "Rodolfo",
    "last_name": "Ciobutaru",
    "email": "rciobutaru9@unblog.fr",
    "gender": "Agender",
    "ip_address": "216.63.163.0"
  }]

module.exports = students